version: '3'
services:
    db:
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=slack-clone
            - POSTGRES_PASSWORD=password
    mercure:
        image: dunglas/mercure
